spring.application.name=monitoringPal

### [1] batch job DB
spring.datasource.domain.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.domain.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/study_pal?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.domain.username=${MYSQL_USER}
spring.datasource.domain.password=${MYSQL_PWD}
spring.datasource.domain.hikari.auto-commit=false
spring.datasource.domain.hikari.pool-name=DomainHikariCP

### [2] meta data DB
spring.datasource.meta.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.meta.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/study_pal_batch?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.meta.username=${MYSQL_USER}
spring.datasource.meta.password=${MYSQL_PWD}
spring.datasource.meta.hikari.pool-name=MetaHikariCP

### [3] monitoring DB
spring.datasource.monitor.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.monitor.jdbc-url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/monitor?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
spring.datasource.monitor.username=${MYSQL_USER}
spring.datasource.monitor.password=${MYSQL_PWD}
spring.datasource.monitor.hikari.pool-name=MetaHikariCP


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.database=0
#redis connection pool setting
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0
spring.data.redis.jedis.pool.max-wait=-1ms
#redis template setting
spring.data.redis.timeout=2000ms